-- Insert real AI agents data
INSERT INTO agents (
  name, slug, description, category_slug, pricing, source_type, 
  popularity, autonomy, users_count, author_name, author_avatar,
  image_url, tags, featured, github_url, demo_url, website_url
) VALUES
(
  'Vercel AI SDK',
  'vercel-ai-sdk',
  'Free open-source TypeScript SDK for building LLM-powered apps and agents across frameworks with unified API.',
  'development',
  'free',
  'open-source',
  92,
  4,
  45000,
  'Vercel',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['TypeScript', 'SDK', 'LLM', 'Framework'],
  true,
  'https://github.com/vercel/ai',
  'https://sdk.vercel.ai',
  'https://vercel.com/ai'
),
(
  'Unitree R1',
  'unitree-r1',
  'Ultra-lightweight humanoid robot with 26 joints, multimodal AI, priced for research and education.',
  'robotics',
  'paid',
  'closed-source',
  82,
  48,
  1200,
  'Unitree Robotics',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Humanoid', 'Robot', 'Multimodal', 'Research'],
  true,
  null,
  'https://unitree.com/r1',
  'https://unitree.com'
),
(
  'GLM-4.5',
  'glm-4-5',
  'Open-source hybrid-reasoning MoE foundation model optimized for intelligent agent tasks with 128K context and tool use.',
  'ai-assistant',
  'free',
  'open-source',
  79,
  84,
  28000,
  'Zhipu AI',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['MoE', 'Foundation Model', 'Tool Use', '128K Context'],
  true,
  'https://github.com/THUDM/GLM-4',
  null,
  'https://zhipuai.cn'
),
(
  'AutoGPT',
  'autogpt',
  'Autonomous AI agent that can perform tasks independently by breaking them down into sub-tasks and executing them.',
  'automation',
  'freemium',
  'open-source',
  88,
  92,
  67000,
  'Significant Gravitas',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Autonomous', 'Task Planning', 'GPT-4', 'Web Browsing'],
  true,
  'https://github.com/Significant-Gravitas/AutoGPT',
  null,
  'https://agpt.co'
),
(
  'LangChain',
  'langchain',
  'Framework for developing applications powered by language models with chains, agents, and memory capabilities.',
  'development',
  'free',
  'open-source',
  95,
  15,
  89000,
  'LangChain Inc',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Framework', 'Chains', 'Memory', 'Tools'],
  true,
  'https://github.com/langchain-ai/langchain',
  null,
  'https://langchain.com'
),
(
  'CrewAI',
  'crewai',
  'Framework for orchestrating role-playing, autonomous AI agents to collaborate and complete complex tasks.',
  'ai-assistant',
  'freemium',
  'open-source',
  76,
  78,
  23000,
  'CrewAI Inc',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Multi-Agent', 'Role-Playing', 'Collaboration', 'Tasks'],
  false,
  'https://github.com/joaomdmoura/crewAI',
  null,
  'https://crewai.com'
),
(
  'Anthropic Claude',
  'anthropic-claude',
  'Constitutional AI assistant focused on being helpful, harmless, and honest with advanced reasoning capabilities.',
  'chatbot',
  'paid',
  'closed-source',
  91,
  65,
  156000,
  'Anthropic',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Constitutional AI', 'Reasoning', 'Safety', 'Helpful'],
  true,
  null,
  'https://claude.ai',
  'https://anthropic.com'
),
(
  'Midjourney',
  'midjourney',
  'AI-powered image generation tool that creates stunning artwork and designs from text descriptions.',
  'design',
  'paid',
  'closed-source',
  94,
  25,
  234000,
  'Midjourney Inc',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Image Generation', 'Art', 'Creative', 'Text-to-Image'],
  true,
  null,
  'https://midjourney.com',
  'https://midjourney.com'
),
(
  'Zapier AI Actions',
  'zapier-ai-actions',
  'Connect AI agents to 6000+ apps with natural language automation and workflow orchestration.',
  'automation',
  'freemium',
  'closed-source',
  85,
  56,
  78000,
  'Zapier',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Automation', 'Integrations', 'Workflow', 'Natural Language'],
  false,
  null,
  'https://zapier.com/ai',
  'https://zapier.com'
),
(
  'Perplexity AI',
  'perplexity-ai',
  'AI-powered search engine that provides accurate answers with real-time information and source citations.',
  'ai-assistant',
  'freemium',
  'closed-source',
  87,
  42,
  145000,
  'Perplexity AI',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Search', 'Real-time', 'Citations', 'Research'],
  false,
  null,
  'https://perplexity.ai',
  'https://perplexity.ai'
),
(
  'Cursor AI',
  'cursor-ai',
  'AI-powered code editor that helps developers write, edit, and debug code with intelligent suggestions.',
  'development',
  'freemium',
  'closed-source',
  83,
  35,
  34000,
  'Anysphere',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Code Editor', 'AI Suggestions', 'Debugging', 'IDE'],
  false,
  null,
  'https://cursor.sh',
  'https://cursor.sh'
),
(
  'Runway ML',
  'runway-ml',
  'AI-powered creative suite for video generation, editing, and visual effects with cutting-edge models.',
  'video',
  'freemium',
  'closed-source',
  89,
  28,
  67000,
  'Runway AI',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Video Generation', 'Creative', 'Visual Effects', 'AI Models'],
  true,
  null,
  'https://runwayml.com',
  'https://runwayml.com'
),
(
  'GitHub Copilot',
  'github-copilot',
  'AI pair programmer that helps you write code faster with intelligent code completions and suggestions.',
  'development',
  'paid',
  'closed-source',
  96,
  45,
  125000,
  'GitHub',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Code Completion', 'AI Programming', 'IDE Integration', 'Productivity'],
  true,
  null,
  'https://github.com/features/copilot',
  'https://github.com/features/copilot'
),
(
  'Stable Diffusion',
  'stable-diffusion',
  'Open-source text-to-image diffusion model capable of generating detailed images from text descriptions.',
  'design',
  'free',
  'open-source',
  93,
  20,
  189000,
  'Stability AI',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Text-to-Image', 'Diffusion', 'Open Source', 'Art Generation'],
  true,
  'https://github.com/Stability-AI/StableDiffusion',
  'https://huggingface.co/spaces/stabilityai/stable-diffusion',
  'https://stability.ai'
),
(
  'ChatGPT',
  'chatgpt',
  'Advanced conversational AI that can assist with writing, analysis, math, coding, and creative tasks.',
  'chatbot',
  'freemium',
  'closed-source',
  98,
  75,
  267000,
  'OpenAI',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Conversational AI', 'GPT-4', 'Multimodal', 'General Purpose'],
  true,
  null,
  'https://chat.openai.com',
  'https://openai.com/chatgpt'
),
(
  'ElevenLabs',
  'elevenlabs',
  'AI voice generator that creates realistic speech in any voice and style with advanced voice cloning technology.',
  'audio',
  'freemium',
  'closed-source',
  86,
  30,
  45000,
  'ElevenLabs',
  '/placeholder-user.jpg',
  '/placeholder.jpg',
  ARRAY['Voice Synthesis', 'Voice Cloning', 'Text-to-Speech', 'Audio AI'],
  false,
  null,
  'https://elevenlabs.io',
  'https://elevenlabs.io'
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_slug = EXCLUDED.category_slug,
  pricing = EXCLUDED.pricing,
  source_type = EXCLUDED.source_type,
  popularity = EXCLUDED.popularity,
  autonomy = EXCLUDED.autonomy,
  users_count = EXCLUDED.users_count,
  author_name = EXCLUDED.author_name,
  author_avatar = EXCLUDED.author_avatar,
  image_url = EXCLUDED.image_url,
  tags = EXCLUDED.tags,
  featured = EXCLUDED.featured,
  github_url = EXCLUDED.github_url,
  demo_url = EXCLUDED.demo_url,
  website_url = EXCLUDED.website_url,
  updated_at = CURRENT_TIMESTAMP;
