@@ .. @@
 INSERT INTO agents (
-  name, slug, description, category_slug, pricing, source_type, 
+  name, slug, description, category, pricing, source_type, 
   popularity, autonomy, users_count, author_name, author_avatar,
   image_url, tags, featured, github_url, demo_url, website_url
 ) VALUES
 (
   'Vercel AI SDK',
   'vercel-ai-sdk',
   'Free open-source TypeScript SDK for building LLM-powered apps and agents across frameworks with unified API.',
-  'development',
+  'development',
   'free',
   'open-source',
   92,
@@ .. @@
   'Unitree R1',
   'unitree-r1',
   'Ultra-lightweight humanoid robot with 26 joints, multimodal AI, priced for research and education.',
-  'robotics',
+  'robotics',
   'paid',
   'closed-source',
   82,
@@ .. @@
   'GLM-4.5',
   'glm-4-5',
   'Open-source hybrid-reasoning MoE foundation model optimized for intelligent agent tasks with 128K context and tool use.',
-  'ai-assistant',
+  'ai-assistant',
   'free',
   'open-source',
   79,
@@ .. @@
   'AutoGPT',
   'autogpt',
   'Autonomous AI agent that can perform tasks independently by breaking them down into sub-tasks and executing them.',
-  'automation',
+  'automation',
   'freemium',
   'open-source',
   88,
@@ .. @@
   'LangChain',
   'langchain',
   'Framework for developing applications powered by language models with chains, agents, and memory capabilities.',
-  'development',
+  'development',
   'free',
   'open-source',
   95,
@@ .. @@
   'CrewAI',
   'crewai',
   'Framework for orchestrating role-playing, autonomous AI agents to collaborate and complete complex tasks.',
-  'ai-assistant',
+  'ai-assistant',
   'freemium',
   'open-source',
   76,
@@ .. @@
   'Anthropic Claude',
   'anthropic-claude',
   'Constitutional AI assistant focused on being helpful, harmless, and honest with advanced reasoning capabilities.',
-  'chatbot',
+  'chatbot',
   'paid',
   'closed-source',
   91,
@@ .. @@
   'Midjourney',
   'midjourney',
   'AI-powered image generation tool that creates stunning artwork and designs from text descriptions.',
-  'design',
+  'design',
   'paid',
   'closed-source',
   94,
@@ .. @@
   'Zapier AI Actions',
   'zapier-ai-actions',
   'Connect AI agents to 6000+ apps with natural language automation and workflow orchestration.',
-  'automation',
+  'automation',
   'freemium',
   'closed-source',
   85,
@@ .. @@
   'Perplexity AI',
   'perplexity-ai',
   'AI-powered search engine that provides accurate answers with real-time information and source citations.',
-  'ai-assistant',
+  'ai-assistant',
   'freemium',
   'closed-source',
   87,
@@ .. @@
   'Cursor AI',
   'cursor-ai',
   'AI-powered code editor that helps developers write, edit, and debug code with intelligent suggestions.',
-  'development',
+  'development',
   'freemium',
   'closed-source',
   83,
@@ .. @@
   'Runway ML',
   'runway-ml',
   'AI-powered creative suite for video generation, editing, and visual effects with cutting-edge models.',
-  'video',
+  'video',
   'freemium',
   'closed-source',
   89,
@@ .. @@
   'GitHub Copilot',
   'github-copilot',
   'AI pair programmer that helps you write code faster with intelligent code completions and suggestions.',
-  'development',
+  'development',
   'paid',
   'closed-source',
   96,
@@ .. @@
   'Stable Diffusion',
   'stable-diffusion',
   'Open-source text-to-image diffusion model capable of generating detailed images from text descriptions.',
-  'design',
+  'design',
   'free',
   'open-source',
   93,
@@ .. @@
   'ChatGPT',
   'chatgpt',
   'Advanced conversational AI that can assist with writing, analysis, math, coding, and creative tasks.',
-  'chatbot',
+  'chatbot',
   'freemium',
   'closed-source',
   98,
@@ .. @@
   'ElevenLabs',
   'elevenlabs',
   'AI voice generator that creates realistic speech in any voice and style with advanced voice cloning technology.',
-  'audio',
+  'audio',
   'freemium',
   'closed-source',
   86,
@@ .. @@
 ON CONFLICT (slug) DO UPDATE SET
   name = EXCLUDED.name,
   description = EXCLUDED.description,
-  category_slug = EXCLUDED.category_slug,
+  category = EXCLUDED.category,
   pricing = EXCLUDED.pricing,
   source_type = EXCLUDED.source_type,
   popularity = EXCLUDED.popularity,